### ISSUE TITLE
Installation error with python3.5

### ISSUE THREAD

**Issue by dhhagan** [darothen/py-mie#4]
After installing (presumably) correctly on python3.5, I get an ImportError:

    ImportErrror: No module named 'mie._mie'

**Comment by twmr** [comment]
Did you start your script from within the py-mie directory?

**Comment by dhhagan** [comment]
@thisch Yes. It appears to install correctly, which I find strange if it truly can't locate the extensions...

**Comment by dhhagan** [comment]
I fixed this by adding support for setuptools installation rather than numpy.distutils.core

I'm not sure why that worked, but it did..

**Comment by darothen** [comment]
Building for Python 3.5 [works on Travis](https://travis-ci.org/darothen/py-mie/builds/109473198), so more investigation is needed here.

**Comment by imanyakin** [comment]
Same thing happens on python 2.7.12

`
======================================================================
ERROR: Failure: ImportError (No module named _mie)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/ilya/workspace/py-mie/mie/__init__.py", line 4, in <module>
    from .mie import *
  File "/home/ilya/workspace/py-mie/mie/mie.py", line 3, in <module>
    from ._mie import dmiess_module as dmiess
ImportError: No module named _mie

----------------------------------------------------------------------
Ran 1 test in 0.035s
`

**Comment by darothen** [comment]
@imanyakin That class of error usually arises when the module has not been successfully built.
